# Main
# 0.4

enabled: true

# Use actionbar instead of chat messages
actionbar: true

# Protections
# Protect from other players.

# Protect pets completely while player is offline?
offline-protect: true

# Prevents different kinds of interactions
hurt: true
ride: true
access: true


# Messages
# {pet} = Pet name / {owner} = Owner username

# Message to show if an attempted interaction is made
message: "&b{pet}&r is owned by &o{owner}"

# Alternative Message if the owner cannot be found
altmessage: "&b{pet}&r is protected!"

# Allow showing custom pet names?
customname: true
