# PetProtect v0.3.2
# GitHub: https://github.com/Vencorr/PetProtect
# Spigot: https://www.spigotmc.org/resources/petprotect.69950/

# This completely disables the plugin on startup if set to false
enabled: true

# ===========
# Prevent Hurt
# ===========
# pet-invulnerable - Make pets invulnerable to the environment (blocks)
# owner-protect - Prevent owners from hitting their pets
# hurt - Protect against hurt
# ride - Protect against riding
# access - Protect against leads and inventory access
# exclude - Not yet implemented (0.3.x will do nothing with it)

pet-invulnerable: true
owner-protect: true
hurt: true
ride: true
access: true
exclude: []

# ========
# Messages
# ========
# {pet} = Pet name / {owner} = Owner username
# messagetype - Type of message (0 = none, 1 = chat, 2 = actionbar)
# actionbar - Whether to use actionbar for messages. Disabling this sends messages through chat
# message - Message shown to player if interacting with pet that is not theirs
# altmessage - Message shown to player if interacting with pet that has no owner or if the player is the owner
# customname - Whether to use custom names from pets for messages

messagetype: 2
message: "&b{pet}&r is owned by &o{owner}"
altmessage: "&b{pet}&r is protected"
customname: true
