# Main
# 0.3

enabled: true

# Use actionbar instead of chat messages
actionbar: true

# Protections
# Protect from other players.

# Protect pets completely while player is offline?
offline-protect: true

# Prevent Hurt
hurt: true

# Prevent Riding
ride: true

# Prevent Accessing
access: true


# Messages
# {pet} = Pet name / {owner} = Owner username

# Message to show if an attempted interaction is made
message: "&b{pet}&r is owned by &o{owner}"

# Alternative Message if the owner cannot be found
altmessage: "You cannot hurt &b{pet}"

# Allow showing custom pet names?
customname: true
